INSERT INTO glass_type (name, size_ml, description) VALUES ('Martini', 140, 'Plastic Martini glass from Amazon seller');
INSERT INTO glass_type (name, size_ml, description) VALUES ('Plastic Tumbler', 170, 'The other plastic which has already been bought');
INSERT INTO glass_type (name, size_ml, description) VALUES ('Highball', 200, 'Glass from hsnotts kitchen');
INSERT INTO glass_type (name, size_ml, description) VALUES ('Small Wine Glass', 180, 'Glass from hsnotts kitchen');
INSERT INTO glass_type (name, size_ml, description) VALUES ('Tumbler', 200, 'Glass from hsnotts kitchen');
INSERT INTO glass_type (name, size_ml, description) VALUES ('Paper Coffee Cup', 240, 'Disposable mugs from previous hackspace event (brown outer)');

INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Optic', 'ml', 'ml', 25, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Mixer Tap', 'ml', 'ml', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Dasher', 'dash', 'dashes', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Syringe', 'ml', 'ml', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Conveyor', '', '', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Stirrer', 'stir', 'stirs', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Slice Dispenser', 'slice', 'slices', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Umbrella Dropper', 'umbrella', 'umbrellas', 1, 0);
INSERT INTO dispenser_type (name, unit_name, unit_plural, unit_size, manual) VALUES ('Manual', '', '', 1, 1);

INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Absinthe', id, 300, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Agave Syrup', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Dasher';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Angostura Bitters', id, 0, 1, 1 FROM dispenser_type WHERE name = 'Dasher';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Apple Juice', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Bailey''s Irish Creme', id, 4000, 1, 0 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Bitter Lemon', id, 10, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Blackcurrant Cordial', id, 30, 0, 1 FROM dispenser_type WHERE name = 'Syringe';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Bourbon', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Brandy', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Brown Sugar', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Cinnamon', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Cocoa Powder', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Cointreau', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Cola', id, 10, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Cranberry Juice', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Dark Rum', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Gin', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Ginger Ale', id, 10, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Glace Cherry', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Conveyor';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Grenadine', id, 30, 0, 1 FROM dispenser_type WHERE name = 'Syringe';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Ice', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Ice Tea', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Kahlua', id, 3200, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Lemon Juice', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Dasher';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Lemon Slice', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Slice Dispenser';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Lemonade', id, 10, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Lime Juice', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Dasher';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Lime Slice', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Slice Dispenser';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Mango Juice', id, 20, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Maraschino Cherry', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Umbrella Dropper';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Nutmeg', id, 0, 0, 0 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Olive', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Conveyor';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Orange Juice', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Ouzo', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Peach Schnapps', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Pepper', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Pernod', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Pineapple Juice', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Port', id, 3500, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Red Grape Juice', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Rum', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Salt', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Sambuca', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Soda Water', id, 10, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Soy Sauce', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Spiced Rum', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Stir', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Stirrer';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Sugar Cube', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Manual';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Sweet Sherry', id, 3500, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Tequila', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Tia Maria', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Tobasco Sauce', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Dasher';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Tomato Juice', id, 20, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Tonic Water', id, 10, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Triple Sec', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Umbrella', id, 0, 0, 1 FROM dispenser_type WHERE name = 'Umbrella Dropper';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Vodka', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Whisky', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'White Grape Juice', id, 25, 0, 1 FROM dispenser_type WHERE name = 'Mixer Tap';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'White Rum', id, 3000, 1, 1 FROM dispenser_type WHERE name = 'Optic';
INSERT INTO ingredient (name, dispenser_type_id, dispenser_param, alcoholic, vegan) SELECT 'Worcestershire Sauce', id, 0, 0, 0 FROM dispenser_type WHERE name = 'Dasher';

INSERT INTO recipe (name, glass_type_id) SELECT 'Adult Beverage', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Amber Glow', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Bacardi Cocktail', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Bacardi Cooler', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Barbados', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Barbados Swizzle', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Barfly''s Dream', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Brass Monkey', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Brompton', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Caprioska', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Carib', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Caribbean Night', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Cocktail Lover', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Cuba Libre', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Cuba Libre Blanco', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Daiquiri', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Death at Sunset', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'EMF Iced Tea', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Fireman''s Sour', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Fitzgerald', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Florida Cocktail', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Flying Tiger', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Fruit Cup', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gimlet', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gin and Orange', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gin and Sin', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gin and Tonic', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gin Cocktail', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gin Fizz', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Gin Sour', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Grand Duchesse', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Grenadina', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Hawaiian Vodka', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Holbeach Molly', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Horse''s Neck', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Indian Summer Shooter', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Island Sunset', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Ivan Collins', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Jackhammer', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'John Collins', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Ladyboy', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Moustache Ride', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'My Fair Lady', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Navy Punch', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Orange Blossom', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Orange Lemonade', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Paralyzer', id FROM glass_type WHERE name = 'Highball';
INSERT INTO recipe (name, glass_type_id) SELECT 'Pikaki', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Pineapple Cocktail', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Pineapple Sour', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Pink Lady', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Planter''s Cocktail', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Planter''s Punch', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Poke', id FROM glass_type WHERE name = 'Highball';
INSERT INTO recipe (name, glass_type_id) SELECT 'President', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Pussy Foot', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Red Thing', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Refresher', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Robinson Crusoe', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Robson', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Ruby Orange', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Rum Collins', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Rum Gimlet', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Rum Sour', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Screwdriver', id FROM glass_type WHERE name = 'Highball';
INSERT INTO recipe (name, glass_type_id) SELECT 'St Clements', id FROM glass_type WHERE name = 'Highball';
INSERT INTO recipe (name, glass_type_id) SELECT 'Sweetie', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Ti Punch', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Touchdown', id FROM glass_type WHERE name = 'Highball';
INSERT INTO recipe (name, glass_type_id) SELECT 'Trophy', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Turing Test', id FROM glass_type WHERE name = 'Highball';
INSERT INTO recipe (name, glass_type_id) SELECT 'Unit Test', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Upton', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Vodka Gimlet', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Vodka Rickey', id FROM glass_type WHERE name = 'Martini';
INSERT INTO recipe (name, glass_type_id) SELECT 'Vodka Sour', id FROM glass_type WHERE name = 'Martini';

INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Vodka Gimlet' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Vodka Gimlet' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 10 FROM recipe r, ingredient i WHERE r.name = 'Vodka Gimlet' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Grand Duchesse' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Grand Duchesse' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Grand Duchesse' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Grand Duchesse' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Ivan Collins' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Ivan Collins' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 30, 10 FROM recipe r, ingredient i WHERE r.name = 'Ivan Collins' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Ivan Collins' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 0 FROM recipe r, ingredient i WHERE r.name = 'Screwdriver' AND i.name = 'Ice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Screwdriver' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 75, 25 FROM recipe r, ingredient i WHERE r.name = 'Screwdriver' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Vodka Sour' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Vodka Sour' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Vodka Sour' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Orange Blossom' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Orange Blossom' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gimlet' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Gimlet' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 10 FROM recipe r, ingredient i WHERE r.name = 'Gimlet' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gin Cocktail' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 3, 0 FROM recipe r, ingredient i WHERE r.name = 'Gin Cocktail' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Pink Lady' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Pink Lady' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Pink Lady' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gin and Sin' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 25 FROM recipe r, ingredient i WHERE r.name = 'Gin and Sin' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Gin and Sin' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Gin and Sin' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Barfly''s Dream' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Barfly''s Dream' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 25, 25 FROM recipe r, ingredient i WHERE r.name = 'Barfly''s Dream' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'My Fair Lady' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 25 FROM recipe r, ingredient i WHERE r.name = 'My Fair Lady' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'My Fair Lady' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 1, 30 FROM recipe r, ingredient i WHERE r.name = 'My Fair Lady' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'John Collins' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'John Collins' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'John Collins' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'John Collins' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gin and Tonic' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 10 FROM recipe r, ingredient i WHERE r.name = 'Gin and Tonic' AND i.name = 'Tonic Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gin Fizz' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Gin Fizz' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Gin Fizz' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Gin Fizz' AND i.name = 'Sugar Cube';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gin Sour' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Gin Sour' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Gin Sour' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Gin Sour' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Gin and Orange' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Gin and Orange' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'EMF Iced Tea' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'EMF Iced Tea' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'EMF Iced Tea' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'EMF Iced Tea' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'EMF Iced Tea' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 6, 30, 10 FROM recipe r, ingredient i WHERE r.name = 'EMF Iced Tea' AND i.name = 'Cola';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Amber Glow' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Amber Glow' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 15, 0 FROM recipe r, ingredient i WHERE r.name = 'Amber Glow' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Amber Glow' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Amber Glow' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Cocktail' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Cocktail' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Cocktail' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Daiquiri' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Daiquiri' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Daiquiri' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Daiquiri' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cocktail' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cocktail' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cocktail' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Robson' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Robson' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 25 FROM recipe r, ingredient i WHERE r.name = 'Robson' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Robson' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Rum Gimlet' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Rum Gimlet' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Rum Gimlet' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'President' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'President' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'President' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Upton' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Upton' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 25 FROM recipe r, ingredient i WHERE r.name = 'Upton' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Upton' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Carib' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Carib' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Carib' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Carib' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Robinson Crusoe' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Robinson Crusoe' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Trophy' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Trophy' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Trophy' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 3, 0 FROM recipe r, ingredient i WHERE r.name = 'Trophy' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Pikaki' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Pikaki' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Pikaki' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Pikaki' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Punch' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Punch' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Punch' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Punch' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Punch' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 6, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Planter''s Punch' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 30, 10 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre' AND i.name = 'Cola';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Rum Sour' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Rum Sour' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Rum Sour' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Rum Collins' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Rum Collins' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Rum Collins' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Rum Collins' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cooler' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cooler' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cooler' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Bacardi Cooler' AND i.name = 'Tonic Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Caribbean Night' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Caribbean Night' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Caribbean Night' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Caribbean Night' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Barbados' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Barbados' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Barbados' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Barbados' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Barbados' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Fireman''s Sour' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Fireman''s Sour' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Fireman''s Sour' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 30, 10 FROM recipe r, ingredient i WHERE r.name = 'Fireman''s Sour' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Navy Punch' AND i.name = 'Dark Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Navy Punch' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Navy Punch' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Navy Punch' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Barbados Swizzle' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Barbados Swizzle' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Barbados Swizzle' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Barbados Swizzle' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Fitzgerald' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Fitzgerald' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Fitzgerald' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Fitzgerald' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Ti Punch' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Ti Punch' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Ti Punch' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Vodka Rickey' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Vodka Rickey' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Vodka Rickey' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 30, 10 FROM recipe r, ingredient i WHERE r.name = 'Vodka Rickey' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Island Sunset' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Island Sunset' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 2, 30 FROM recipe r, ingredient i WHERE r.name = 'Island Sunset' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Death at Sunset' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Death at Sunset' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Death at Sunset' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Moustache Ride' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 10 FROM recipe r, ingredient i WHERE r.name = 'Moustache Ride' AND i.name = 'Cola';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Brompton' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Brompton' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 50, 10 FROM recipe r, ingredient i WHERE r.name = 'Brompton' AND i.name = 'Cola';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Flying Tiger' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Flying Tiger' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Flying Tiger' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Flying Tiger' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Jackhammer' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Jackhammer' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Cocktail Lover' AND i.name = 'Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Cocktail Lover' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Cocktail Lover' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Cocktail Lover' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Hawaiian Vodka' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 25 FROM recipe r, ingredient i WHERE r.name = 'Hawaiian Vodka' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Hawaiian Vodka' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Hawaiian Vodka' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Hawaiian Vodka' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Holbeach Molly' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 75, 10 FROM recipe r, ingredient i WHERE r.name = 'Holbeach Molly' AND i.name = 'Tonic Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Holbeach Molly' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Holbeach Molly' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Brass Monkey' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Brass Monkey' AND i.name = 'Vodka';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Brass Monkey' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Sweetie' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Sweetie' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Sweetie' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Pineapple Sour' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Pineapple Sour' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Pineapple Sour' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Pineapple Cocktail' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Pineapple Cocktail' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Grenadina' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Grenadina' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 40, 10 FROM recipe r, ingredient i WHERE r.name = 'Grenadina' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Florida Cocktail' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Florida Cocktail' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Florida Cocktail' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Florida Cocktail' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Pussy Foot' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 25 FROM recipe r, ingredient i WHERE r.name = 'Pussy Foot' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Pussy Foot' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Pussy Foot' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 40, 25 FROM recipe r, ingredient i WHERE r.name = 'Ruby Orange' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Ruby Orange' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Ruby Orange' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Fruit Cup' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Fruit Cup' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Fruit Cup' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 5, 30 FROM recipe r, ingredient i WHERE r.name = 'Fruit Cup' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Orange Lemonade' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Orange Lemonade' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Orange Lemonade' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Orange Lemonade' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 30, 25 FROM recipe r, ingredient i WHERE r.name = 'Refresher' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Refresher' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 20, 10 FROM recipe r, ingredient i WHERE r.name = 'Refresher' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Red Thing' AND i.name = 'Orange Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 20, 25 FROM recipe r, ingredient i WHERE r.name = 'Red Thing' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Red Thing' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 10, 30 FROM recipe r, ingredient i WHERE r.name = 'Red Thing' AND i.name = 'Grenadine';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 10 FROM recipe r, ingredient i WHERE r.name = 'Adult Beverage' AND i.name = 'Soda Water';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Adult Beverage' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 5, 0 FROM recipe r, ingredient i WHERE r.name = 'Adult Beverage' AND i.name = 'Lemon Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 3, 0 FROM recipe r, ingredient i WHERE r.name = 'Adult Beverage' AND i.name = 'Agave Syrup';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 2, 0 FROM recipe r, ingredient i WHERE r.name = 'Adult Beverage' AND i.name = 'Angostura Bitters';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 0 FROM recipe r, ingredient i WHERE r.name = 'Turing Test' AND i.name = 'Ice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 2, 3000 FROM recipe r, ingredient i WHERE r.name = 'Turing Test' AND i.name = 'Gin';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 25, 25 FROM recipe r, ingredient i WHERE r.name = 'Turing Test' AND i.name = 'Pineapple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 50, 25 FROM recipe r, ingredient i WHERE r.name = 'Turing Test' AND i.name = 'Apple Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 5, 1, 0 FROM recipe r, ingredient i WHERE r.name = 'Turing Test' AND i.name = 'Lime Slice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Unit Test' AND i.name = 'Whisky';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 1, 50, 0 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre Blanco' AND i.name = 'Ice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 2, 1, 3000 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre Blanco' AND i.name = 'White Rum';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 3, 10, 0 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre Blanco' AND i.name = 'Lime Juice';
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, seq, qty, dispenser_param) SELECT r.id, i.id, 4, 50, 10 FROM recipe r, ingredient i WHERE r.name = 'Cuba Libre Blanco' AND i.name = 'Cola';

INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 1, dispenser_type_id, id, 'Optic 0', 0 FROM ingredient WHERE name = 'Vodka';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 2, dispenser_type_id, id, 'Optic 1', 546 FROM ingredient WHERE name = 'Vodka';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 3, dispenser_type_id, id, 'Optic 2', 1093 FROM ingredient WHERE name = 'Vodka';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 4, dispenser_type_id, id, 'Optic 3', 1640 FROM ingredient WHERE name = 'White Rum';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 5, dispenser_type_id, id, 'Optic 4', 2187 FROM ingredient WHERE name = 'Tequila';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 6, dispenser_type_id, id, 'Optic 5', 2734 FROM ingredient WHERE name = 'Gin';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 7, dispenser_type_id, id, 'Mixer 0', 3117 FROM ingredient WHERE name = 'Orange Juice';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 8, dispenser_type_id, id, 'Mixer 1', 3417 FROM ingredient WHERE name = 'Pineapple Juice';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 9, dispenser_type_id, id, 'Mixer 2', 3746 FROM ingredient WHERE name = 'Cranberry Juice';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 10, dispenser_type_id, id, 'Mixer 3', 4057 FROM ingredient WHERE name = 'Tonic Water';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 11, dispenser_type_id, id, 'Mixer 4', 4357 FROM ingredient WHERE name = 'Soda Water';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 12, dispenser_type_id, id, 'Mixer 5', 4714 FROM ingredient WHERE name = 'Cola';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 13, dispenser_type_id, id, 'Dasher 0', 5058 FROM ingredient WHERE name = 'Angostura Bitters';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 14, dispenser_type_id, id, 'Dasher 1', 5332 FROM ingredient WHERE name = 'Lemon Juice';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 15, dispenser_type_id, id, 'Dasher 2', 5550 FROM ingredient WHERE name = 'Agave Syrup';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 16, dispenser_type_id, id, 'Conveyor', 5900 FROM ingredient WHERE name = 'Olive';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 17, dispenser_type_id, id, 'Syringe', 6150 FROM ingredient WHERE name = 'Grenadine';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 18, dispenser_type_id, id, 'Slice Dispenser', 6525 FROM ingredient WHERE name = 'Lime Slice';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 19, dispenser_type_id, id, 'Stirrer', 6825 FROM ingredient WHERE name = 'Stir';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 20, dispenser_type_id, id, 'Umbrella Dropper', 7080 FROM ingredient WHERE name = 'Maraschino Cherry';
INSERT INTO dispenser (id, dispenser_type_id, ingredient_id, name, rail_position) SELECT 21, dispenser_type_id, id, 'Manual', 7080 FROM ingredient WHERE name = 'Ice';

