# TO use this Makefile to build the code in this directory, install the arduino-mk package
# (on debian based dsitros)

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = AccelStepper Servo BarBot
USER_LIB_PATH := $(realpath ../lib)

include /usr/share/arduino/Arduino.mk


